### ISSUE TITLE
the program doesn't allow - and \

### ISSUE THREAD

**Issue by pmxi** [itsmichaelyu/punctuation#4]
it is also missing more characters
https://en.wikipedia.org/wiki/List_of_typographical_symbols_and_punctuation_marks

**Comment by itsmichaelyu** [comment]
not punctuation

**Comment by pmxi** [comment]
- is literally punctuation!! and if / counts, then \ does too

**Comment by pmxi** [comment]
> The hyphen ‐ is a [punctuation](https://en.wikipedia.org/wiki/Punctuation) mark used to join [words](https://en.wikipedia.org/wiki/Word) and to separate [syllables](https://en.wikipedia.org/wiki/Syllable) of a single word.

**Comment by itsmichaelyu** [comment]
Fine, I will add everything in [here](https://glitch.com/edit/#!/just-the-punctuation?path=script.js%3A1%3A0)

**Comment by itsmichaelyu** [comment]
Is that enough symbols for you

**Comment by pmxi** [comment]
Yes, that is better.
